### ISSUE TITLE
How to import this library

### ISSUE THREAD

**Issue by mithrann** [Tibolte/AgendaCalendarView#1]
Hi,
Can you share the screen of how it will look.

Thanks

**Comment by Tibolte** [comment]
I invite you to try the sample app for now. I need to finalize some details.

I'll make it available to import via Gradle.

**Comment by mithrann** [comment]
I couldn't able to get the sample to working.. its showing error.

**Comment by Tibolte** [comment]
I see the manifests are missing, my mistake, probably that. I'll fix it today and reply here.

**Comment by mithrann** [comment]
Thank you :)

**Comment by mithrann** [comment]
Thank you.. If its not a trouble.. if actually looking to something similar to http://stackoverflow.com/questions/27852947/source-code-for-new-android-lollipop-calendar-app
this. So will this library render this kind of view?

**Comment by Tibolte** [comment]
that's the idea :)

**Comment by mithrann** [comment]
Awesome :+1:

**Comment by Tibolte** [comment]
you can try again!

**Comment by mithrann** [comment]
ok. will do

**Comment by mithrann** [comment]
Great work man .. thanks :+1:

**Comment by mithrann** [comment]
Hi,
I am not able to use this library in the other project. Is there anything that i am missing ?

Thanks.

**Comment by Tibolte** [comment]
what do you mean by "the other project"?

**Comment by mithrann** [comment]
i mean if have to use this lib in my project.

**Comment by mithrann** [comment]
I added this library a dependency to my project.
some of the libraries like stickyheader are not recognised in the lib.

**Comment by Tibolte** [comment]
ok like so compile project(':agendacalendarview')?

**Comment by mithrann** [comment]
yeah

**Comment by mithrann** [comment]
<img width="862" alt="screen shot 2015-10-27 at 8 18 42 pm" src="https://cloud.githubusercontent.com/assets/6015930/10761560/f2f1325c-7ce7-11e5-8721-4124142059c8.png">
<img width="690" alt="screen shot 2015-10-27 at 8 19 09 pm" src="https://cloud.githubusercontent.com/assets/6015930/10761571/054fccce-7ce8-11e5-9da2-e176becda686.png">

**Comment by mithrann** [comment]
The libraries that agendacalendarview using is not imported.. Even though they are in the gradle

**Comment by Tibolte** [comment]
that's super weird, not even after a gradle sync?

**Comment by mithrann** [comment]
yeah.. i did sync lot of times..

**Comment by Tibolte** [comment]
I don't have access to your project but from what you tell me, everything seems fine. I'm seeing a couple of problems on StackOverflow similar to that one... Out of curiosity, does your project run?

**Comment by mithrann** [comment]
No. after importing this lib .. Its not running.

**Comment by mithrann** [comment]
Hi,
If its not a trouble . Can you tell me for these libs you are using ?
 compile 'com.squareup.retrofit:retrofit:1.9.0'
 compile 'pl.charmas.android:android-reactive-location:0.6@aar'
 compile 'io.reactivex:rxjava:1.0.+'
 compile 'io.reactivex:rxandroid:0.25.0'
compile 'com.google.collections:google-collections:1.0-rc2'

**Comment by Tibolte** [comment]
About:

compile 'com.squareup.retrofit:retrofit:1.9.0'
compile 'pl.charmas.android:android-reactive-location:0.6@aar'

I'm thinking about removing those, they are used for fetching weather data. If you don't need that you can remove the weather related code and those imports.

compile 'io.reactivex:rxjava:1.0.+'
compile 'io.reactivex:rxandroid:0.25.0'

are necessary. (Event handling)

but compile 'com.google.collections:google-collections:1.0-rc2' I think it can be removed I'll check it.

**Comment by mithrann** [comment]
ok.. Thank you so much.
By (Event handling) you mean Event Bus?

**Comment by Tibolte** [comment]
yeah, that thing :) I'll tell you when it's available on gradle that should solve everything, I'll remove this weather feature, not really necessary.

**Comment by mithrann** [comment]
Ok sure :) . Thanks. I asked that since i am already using compile 'de.greenrobot:eventbus:2.4.0' in my project.

**Comment by Tibolte** [comment]
now available with:

dependencies {
    compile 'com.github.tibolte:agendacalendarview:1.0.0'
}

more versions to come :)
