### ISSUE TITLE
Events are duplicated on the same day

### ISSUE THREAD

**Issue by arkangelx** [Tibolte/AgendaCalendarView#11]
Loading a json file with events that are on the same day but different in detail repeats  those events multiple times. Events also don't appear on the right dates.
![screenshot_2015-12-04-12-04-04 1](https://cloud.githubusercontent.com/assets/559233/11588355/188858f0-9a80-11e5-88c9-5fb442c5d362.png)

**Comment by arkangelx** [comment]
https://www.dropbox.com/sh/omddbhnx9baliwo/AACLa2DOojJaYCWdEbCuJmzJa?dl=0

**Comment by Tibolte** [comment]
@arkangelx It's really hard to tell, but first thing I'd do when I see your event loading task, place:
Calendar startTime = Calendar.getInstance();
Calendar endTime = Calendar.getInstance();
In the loop just below.
I remember having some problem when using same calendar instances for different instances, I'd recommend creating a new Calendar instance for each event.
That might not solve it but I'd start there.

**Comment by arkangelx** [comment]
Tried that...it didn't work then but will try again tho be sure
thanks....ps it loads past events...right?

**Comment by arkangelx** [comment]
Strangely , it worked!!!! Thibault..i owe you  a beer ...that's if you
drink!!!!! Wow thank you. The logic is simple and the only reason i can
think of is that because its a single initialized once (before loop),
changing its state somehow doesn't get retained in the list.. THANK
YOU!!!!  I thought if i have 1000 events in a year would i want to create
so many references in memory, even though its a singleton. Thank you again

On Sat, Dec 5, 2015 at 6:16 PM, Samson Akisanya <info@mobileparadigm.co.uk>
wrote:

> Tried that...it didn't work then but will try again tho be sure
> thanks....ps it loads past events...right?
> On 5 Dec 2015 18:13, "Thibault Guégan" <notifications@github.com> wrote:
>
>> @arkangelx <https://github.com/arkangelx> It's really hard to tell, but
>> first thing I'd do when I see your event loading task, place:
>> Calendar startTime = Calendar.getInstance();
>> Calendar endTime = Calendar.getInstance();
>> In the loop just below.
>> I remember having some problem when using same calendar instances for
>> different instances, I'd recommend creating a new Calendar instance for
>> each event.
>> That might not solve it but I'd start there.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Tibolte/AgendaCalendarView/issues/11#issuecomment-162217144>
>> .
>>
>


-- 
Innovate & Prevail

**Comment by Tibolte** [comment]
That's good news!! I've been into this situation, happy to help. Thanks for the beer!!
p.s: If you think that's solved for you, I'm inviting you to close that issue.

**Comment by arkangelx** [comment]
yeah..done
