### ISSUE TITLE
Not loading events in the new year.

### ISSUE THREAD

**Issue by LeoJHarris** [Tibolte/AgendaCalendarView#12]
Hi, events in the new year are not loading, the last events to load are on the 31st dec, see screenshots for detail including the calendar (just some random test events) and the data in my database (format is american mm//dd/yyyy) that its loading
![fddfsfss](https://cloud.githubusercontent.com/assets/5468757/11588482/ec943c3a-9ae5-11e5-9efe-2dc435dd6ad2.png)
![device-2015-12-05-001513](https://cloud.githubusercontent.com/assets/5468757/11588490/f6b92fc2-9ae5-11e5-8f2a-52861c59effb.png)

. Code for min and max is same as the simple example from android arsenal page    

```
        Calendar minDate;
        Calendar maxDate;
        // minimum and maximum date of our calendar
        // 2 month behind, one year ahead, example: March 2015 <-> May 2015 <-> May 2016
        minDate = Calendar.getInstance();
        maxDate = Calendar.getInstance();

        minDate.add(Calendar.MONTH, -1);
        minDate.set(Calendar.DAY_OF_MONTH, 1);
        maxDate.add(Calendar.YEAR, 1)
```

Should be loading two events on the 1st of jan 2016

I do really like this calendar view, good job and keep it up :)

**Comment by Tibolte** [comment]
Thanks for the feedback, I'll find some time tomorrow and try your example. I don't recall testing events for a new year when doing this library, stupid me.

**Comment by LeoJHarris** [comment]
Hi, just wondering if you've had been able to get this issue solved yet? Thanks!

**Comment by Tibolte** [comment]
Not yet, I haven't got time actually!
