### ISSUE TITLE
myAgendaCalendarView.init

### ISSUE THREAD

**Issue by ocnkr** [Tibolte/AgendaCalendarView#136]
Hi, 
According to codes that are shown in Usage, when I tried to do 
                  mAgendaCalendarView.init(eventList, minDate, maxDate, Locale.getDefault(), this);
Android Studio says that "Cannot resolve symbol 'mAgendaCalendarView'", what should I do about it? I am new in Android developing and I can't understand logic of the calendars. 

Thanks in advance.

**Comment by farhancroem** [comment]
Please share your code.
