### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by simongiesen** [Tibolte/AgendaCalendarView#14]
Hi,

anyway to do some localization via code? E.g. german translation for "no events" ?

**Comment by Tibolte** [comment]
it's done by the string agenda_event_no_events, it's available for instance in French in the values-fr folder, default one is in the values folder. I believe we simply need to create a values-de folder with german strings in it for this one :)

**Comment by simongiesen** [comment]
ok, this would mean to compile the library first ... and in runtime?

**Comment by Tibolte** [comment]
Probably not at runtime, the library takes strings from its own module. Providing strings in the app module wouldn't have any effect, as the library don't have access to this one.

**Comment by Garridovic** [comment]
Hi,
you have done a nice job with this library. 

Could you create a spanish value folder? You only need to create a values-es folder and put this in string:


      
        <string name="today">Hoy</string>
        <string name="tomorrow">Mañana</string>
        <string name="agenda_event_day_duration">d</string>
        <string name="agenda_event_all_day">Todo el dia</string>
        <string name="agenda_event_no_events">Sin eventos</string>

        
        <string name="morning">Mañana</string>
        <string name="afternoon">Tarde</string>
        <string name="evening">Noche</string>

**Comment by se-bastiaan** [comment]
> Providing strings in the app module wouldn't have any effect, as the library don't have access to this one.

You can override resources of any library in your application. In the end all the resources are being merged and used as one, so if @Garridovic wants Spanish strings then he can add them in his own resources.

Although, translating the default strings wouldn't be a bad idea.

**Comment by Tibolte** [comment]
Since Spanish strings have been provided I'll include them, thanks @Garridovic . And as @se-bastiaan said you can override them. Otherwise feel free to provide them to me!
