### ISSUE TITLE
Imported into Android Studio for sample -Error:No such property: GROUP for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer

### ISSUE THREAD

**Issue by Artespecialist** [Tibolte/AgendaCalendarView#17]
Hello! First of all congratulations on the project.
One question. I am trying to import the project via the github link, as i understand there is a sample project that i can access via this link. Unfortunately gradle can not complete and gives an error:

Gradle 'AgendaCalendarView-master' project refresh failed
Error:No such property: GROUP for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer 

Your help is appreciated. Thank you.

**Comment by Garridovic** [comment]
Hi!
after a short search I founded that commenting the line 37 in agendacalendarview/build.gradle solves the error.
[Source](http://stackoverflow.com/questions/28450549/errorno-such-property-group-for-class-org-gradle-api-publication-maven-intern)

**Comment by Artespecialist** [comment]
I had to comment / delete this line at position 37 
apply from: 'https://raw.github.com/chrisbanes/gradle-mvn-push/master/gradle-mvn-push.gradle'
 
Yes you are correct... Now it works. Thank you!
