### ISSUE TITLE
How to add support for API > 9

### ISSUE THREAD

**Issue by joielechong** [Tibolte/AgendaCalendarView#26]
Does AgendaCalendarView support API > 9? If not, what should I change in the library to make it support API > 9?

**Comment by se-bastiaan** [comment]
The library supports API level 14 and above. As you could've found in https://github.com/Tibolte/AgendaCalendarView/blob/master/agendacalendarview/build.gradle#L15.

**Comment by joielechong** [comment]
@se-bastiaan sorry because I don't make myself clear. I meant how can add support for API >9, is there any code that should I change like animation property or else?

**Comment by se-bastiaan** [comment]
I believe that you could just download the source, change the minsdk version and change everything that causes problems. That'll provide you the code you need to support API 9 and above.

Although, only 3.0% of the Android users that have the Play Store installed are still using API 10. [API 9 is not even in the charts anymore](http://developer.android.com/about/dashboards/index.html). I'm not sure it is worth the work.

**Comment by joielechong** [comment]
Thank you for the info.

Well, I need to support API 9 because some friends still use the old android version.
