### ISSUE TITLE
I am unable import Agenda Calenderview to my project 

### ISSUE THREAD

**Issue by tanve** [Tibolte/AgendaCalendarView#27]
![issue](https://cloud.githubusercontent.com/assets/12641118/12390007/8ce82f22-be02-11e5-8dc8-be059ed2e7d9.png)
i am unable to import into my project

**Comment by amannepid** [comment]
If you are including it as local library then try to put: apply plugin: 'me.tatarka.retrolambda' in you app/build.gradle and classpath 'me.tatarka:gradle-retrolambda:3.1.0' in project/build.gradle dependencies.

Write back if it does not works.

**Comment by tanve** [comment]
Error:No such property: GROUP for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer is coming

**Comment by amannepid** [comment]
comment out this line in agendacalendarview/build.gradle

//apply from: 'https://raw.github.com/chrisbanes/gradle-mvn-push/master/gradle-mvn-push.gradle'

**Comment by amannepid** [comment]
@tanve is it working ??

**Comment by tanve** [comment]
yah tried that one also not working

**Comment by amannepid** [comment]
it should have worked. after commenting try to sync the project.

**Comment by tanve** [comment]
apply plugin: 'com.android.library'
apply plugin: 'me.tatarka.retrolambda'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    android {
        lintOptions {
            abortOnError false
        }
    }

    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles
getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    sourceSets {
        main {
            assets.srcDirs = ['assets']
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

//apply from: 'https://raw.github.com/chrisbanes/gradle-mvn-push/master/gradle-mvn-push.gradle'

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    // Google libraries
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.google.android.gms:play-services-location:8.3.0'
    compile 'com.android.support:recyclerview-v7:23.1.1'
    compile 'com.google.guava:guava:19.0'
    compile 'com.android.support:design:23.1.1'

    // other libraries
    compile 'se.emilsjolander:stickylistheaders:2.5.2'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'pl.charmas.android:android-reactive-location:0.6@aar'
    compile 'io.reactivex:rxjava:1.0.16'
    compile 'io.reactivex:rxandroid:1.0.1'
}

**Comment by tanve** [comment]
thank you@amannepid

**Comment by amannepid** [comment]
that means it worked ?

**Comment by tanve** [comment]
just completed syncing

**Comment by amannepid** [comment]
nice.. enjoy

**Comment by amannepid** [comment]
@tanve if its working now please close the issue.

**Comment by tanve** [comment]
![image](https://cloud.githubusercontent.com/assets/12641118/12416680/c6e66bdc-bec8-11e5-8b37-5d9c3b8e0f2c.png)

**Comment by amannepid** [comment]
use app: instead of agendaCalendar. works ?

**Comment by amannepid** [comment]
@tanve you can find solution to such issue by google somewhere else as well. Please close the issue if it is solved.

**Comment by Priyanka-Mohanty** [comment]
Got error 
class file for se.emilsjolander.stickylistheaders.StickyListHeadersListView not found
