### ISSUE TITLE
About providing custom item layout for event list

### ISSUE THREAD

**Issue by chaossss** [Tibolte/AgendaCalendarView#3]
After reading your code, I find that, if I want to use my own item layout for event list, I have to finish following operations:

1. create my own xml layout for the item
2. inflate my xml in AgendaAdapter's getView method
3. return my own layout view

But if I add this feature by this way, it means every time I want to change the event list's item or I want to use multiple item layout, I have to change AgendaAdapter's code, which is unbearable.

So I want to know what would u do to add this feature. Maybe I could help finish some easy job : )

**Comment by Tibolte** [comment]
That's a good question, and actually the inflation is made into AgendaEventView, first step would be to move the inflation over to the getView method.

A clean way to do it would be to have something like:
- Provide the library an adapter extending the AgendaAdapter class and override getView()
- Provide our own layout there in this method and let the parent class handle the rest

This might not be the correct way, perhaps there is a better one, this is only my first idea. Thoughts?

**Comment by chaossss** [comment]
I have the same idea as yours, and I could use my own layout for event list item. But it is not a good solution and I'm trying to refractor some code. The reason is listed as follows, do u have any good ideas?

1.Because the AgendaListView is subclass of StickyListHeadersListView, it means every item in AgendaListView should set martginLeft, or the AgendaListView would display as this img:

![](http://img.my.csdn.net/uploads/201511/19/1447922750_5547.png)

So if we should set marginLeft.

In AgendaEventView's layout, the marginLeft is 75dp(paddingLeft 15dp + marginLeft 55dp + marginLeft 5dp). After setting it, work is done.

To sum up, if user want to use their own layout, not only should they define layout xml, create the subclass of AgendaAdapter, but also they have to set specified marginLeft to keep this widget's layout(maybe multiple layout xml for adapting different device). 

2.In AgendaAdapter, we've defined CalendarEvent as event item's model. But the problem is, when we customized event item, the content filled into item would possibly change. 

So when we create a subclass of AgendaAdapter, the process would look like:

- Create a model class to fill data into custom event item
- Create a subclass of AgendaAdapter. In subclass's field, we should define a data structure to save the model class.
- Fill data into event item.

And AgendaAdapter would hold the reference of mEvents(List<CalendarEvent>) all the time, though it has no data. Therefore, for storing data, we have to add or change field in subclass if the model has been changed.

**Comment by Tibolte** [comment]
@chaossss something is being done about that at the moment. Could I have your opinion on this if possible? https://github.com/Tibolte/AgendaCalendarView/pull/5

**Comment by chaossss** [comment]
@Tibolte Actually I were preparing to add this feature by the same way as FHellmann, when FHellmann submitted his code, LoL...

So I think the work FHellmann has done is great.

And thanks for u and FHellmann's contribution : )

**Comment by Tibolte** [comment]
Awesome! Thanks for your input @chaossss :)
