### ISSUE TITLE
How can I view a full month

### ISSUE THREAD

**Issue by phongnd93** [Tibolte/AgendaCalendarView#31]
The current calendar show the date and the event of this date but to know that the day of any month is very difficult. So how can I setting the calendar to default show all days of a month. Or how can I show the month on any where ??

**Comment by Tibolte** [comment]
@phongnd93 that is a good catch. Sunrise does it the headers of the StickyListHeaders listview and Google Calendar put the month label in the toolbar.

**Comment by Tibolte** [comment]
@phongnd93 see [this](https://github.com/Tibolte/AgendaCalendarView/pull/36)
