### ISSUE TITLE
gradle error in the sample project 

### ISSUE THREAD

**Issue by mithrann** [Tibolte/AgendaCalendarView#32]
Error:No such property: GROUP for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer

**Comment by fraherm** [comment]
I get the same error when I try to sync Gradle.

**Comment by Tibolte** [comment]
probably related to [Chris Bane's plugin](https://github.com/Tibolte/AgendaCalendarView/blob/master/agendacalendarview/build.gradle#L37)

You don't really need that, @mithrann try to remove it and tell me if that works for you.
