### ISSUE TITLE
Error: java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1 when calling init method

### ISSUE THREAD

**Issue by LeoJHarris** [Tibolte/AgendaCalendarView#34]
Hi, not sure if this is an internal issue, but just recently I have been getting a ArrayIndexOutOfBoundsException when calling init() with my eventslist and the other args. My eventslist definetly has events in the list (from debugging) so not sure why it would be throwing this issue?

More detailed error message below:

ava.lang.ArrayIndexOutOfBoundsException: length=0; index=-1at java.util.ArrayList.get(ArrayList.java:310) at com.github.tibolte.agendacalendarview.CalendarManager.getLastMonth(CalendarManager.java:318 at com.github.tibolte.agendacalendarview.CalendarManager.addWeekToLastMonth(CalendarManager.java:313) com.github.tibolte.agendacalendarview.CalendarManager.buildCal(CalendarManager.java:217) at com.github.tibolte.agendacalendarview.AgendaCalendarView.init(AgendaCalendarView.java:190)
                                                                                       
Is any one else having a similiar issue?

Cheers

**Comment by LeoJHarris** [comment]
Is this repositiory still being worked on?

**Comment by donnaknew** [comment]
Are You set a minDate.add(Calendar.Month, -1); ?

**Comment by LeoJHarris** [comment]
You sir are a god send. Thanks!

**Comment by Tibolte** [comment]
@LeoJHarris sorry I was busy lately, I'm trying to find more time to work on that lib (I actually have to work on it, since the idea is to replace a current calendar widget we are using in one of my company's apps) . Good catch guys, I'll consider this fix.
