### ISSUE TITLE
Support for fragment display

### ISSUE THREAD

**Issue by chilldelta** [Tibolte/AgendaCalendarView#4]
Am trying to use this library with my project on fragment but I get a nullpointer error on mAgendaCalendarView.init() which is not the case when I try this on an activity. Am I doing something wrong?
Here is my code

     @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.planner_fragment_ui, container, false);
        ButterKnife.bind(view, getActivity());
        mAgendaCalendarView = new AgendaCalendarView(getContext());

        Calendar minDate = Calendar.getInstance();
        Calendar maxDate = Calendar.getInstance();

        minDate.add(Calendar.MONTH, -2);
        minDate.set(Calendar.DAY_OF_MONTH, 1);
        maxDate.add(Calendar.YEAR, 1);

        List<CalendarEvent> eventList = new ArrayList<>();
        mockList(eventList);
        mAgendaCalendarView.init(eventList, minDate, maxDate, Locale.getDefault(), this);

        return view;
    }

**Comment by Tibolte** [comment]
When I see your code try: ButterKnife.bind(view, this);

**Comment by chilldelta** [comment]
@Tibolte I fixed the issue without using butterknife by doing
 mAgendaCalendarView = (AgendaCalendarView) view.findViewById(R.id.agenda_calender);

**Comment by Integrale18** [comment]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.tibolte.agendacalendarview.agenda.AgendaAdapter.updateEvents(java.util.List)' on a null object reference
                                                                                                      at com.github.tibolte.agendacalendarview.agenda.AgendaView.lambda$onFinishInflate$8(AgendaView.java:58)

Somebody to help me? i'm using it on Fragment, everything is ok when i use Activity.
