### ISSUE TITLE
How to get BaseCalendarEvent Object on onEventSelected ?

### ISSUE THREAD

**Issue by khalid-mahmood** [Tibolte/AgendaCalendarView#72]
How can i get BaseCalendarEvent  in onEventSelected(CalendarEvent event)  callback ?
i needed all the information of BaseCalendarEvent!

**Comment by onurbarman** [comment]
i solved this 
use this code in onEventSelected
BaseCalendarEvent event1=(BaseCalendarEvent)event.copy();
and write your get :)
exaple rLocation=event1.getLocation();

**Comment by khalid-mahmood** [comment]
Thanks. Its worked..
