### ISSUE TITLE
is it possible to set event for all Sunday on a year ?

### ISSUE THREAD

**Issue by darkhassan** [Tibolte/AgendaCalendarView#76]
i wonder if i chose event periods can i set event to show only in specific day like all Sunday in the month ? 
or all Monday in the year ?

**Comment by AlaaAlShammaa** [comment]
@darkhassan  have you managed to solve this?

**Comment by AlaaAlShammaa** [comment]
@darkhassan 
 `int year = 2016;
        int month = Calendar.AUGUST;
        Calendar cal = new GregorianCalendar(year, month, 1);
        do {
            // get the day of the week for the current day
            int day = cal.get(Calendar.DAY_OF_WEEK);
            // check if it is a Saturday or Sunday
            if (day == Calendar.SUNDAY) {
                // print the day - but you could add them to a list or whatever
                Calendar startTime = Calendar.getInstance();
                startTime.set(Calendar.DAY_OF_MONTH,cal.get(Calendar.DAY_OF_MONTH));
                BaseCalendarEvent event = new BaseCalendarEvent("Visit to Dalvík", "A beautiful small town", "Dalvík",
                        R.color.colorPrimary, startTime, startTime, false);
                eventList.add(event);
            }
            // advance to the next day
            cal.add(Calendar.DAY_OF_YEAR, 1);
        } while (cal.get(Calendar.MONTH) == month);
// stop when we reach the start of the next month`

**Comment by AlaaAlShammaa** [comment]
@darkhassan you could get the date of the days you want to set an event to  :)

``` java
        int year = 2016;
        int month = Calendar.AUGUST;
        Calendar cal = new GregorianCalendar(year, month, 1);
        do {
            // get the day of the week for the current day
            int day = cal.get(Calendar.DAY_OF_WEEK);
            // check if it is a Saturday or Sunday
            if (day == Calendar.SUNDAY) {
                // add the day
                Calendar startTime = Calendar.getInstance();
                startTime.set(Calendar.DAY_OF_MONTH,cal.get(Calendar.DAY_OF_MONTH));
                BaseCalendarEvent event = new BaseCalendarEvent("Visit to Dalvík", "A beautiful small town", "Dalvík",
                        R.color.colorPrimary, startTime, startTime, false);
                eventList.add(event);
            }
            // advance to the next day
            cal.add(Calendar.DAY_OF_YEAR, 1);
        } while (cal.get(Calendar.MONTH) == month);
           // stop when we reach the start of the next month
```
