### ISSUE TITLE
org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer

### ISSUE THREAD

**Issue by wsdjeg** [Tibolte/AgendaCalendarView#8]
No such property: GROUP for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer

**Comment by Tibolte** [comment]
Please provide more context for that, would that be related to Android Studio 2.0?

**Comment by wsdjeg** [comment]
i just use command ./gradlew get this error!fixed by delete`apply from: 'https://raw.github.com/chrisbanes/gradle-mvn-push/master/gradle-mvn-push.gradle'`

**Comment by Tibolte** [comment]
hmm yes you're not supposed to run that, it won't work! What did you intend to do by running ./gradlew?

**Comment by wsdjeg** [comment]
i am using vim for android project

**Comment by Tibolte** [comment]
ok this is surprising, anyway I should not publish this command. thanks for the input

**Comment by wsdjeg** [comment]
thank you ^-^
