### ISSUE TITLE
How to set specific dates for events

### ISSUE THREAD

**Issue by armyofpunk** [Tibolte/AgendaCalendarView#84]
Hi sorry for the dumb question,

I'm trying to set specific dates for my events 

(ie. Fall fair Oct 2 - 4)

thanks

**Comment by Vovusik** [comment]
private void mockList(List<CalendarEvent> eventList) {

        Calendar startTime1 = Calendar.getInstance();
        Calendar endTime1 = Calendar.getInstance();
        startTime1.set(2017, 3, 5);//05.04.17
        endTime1.set(2017, 3, 5);//05.04.17
        BaseCalendarEvent event1 = new BaseCalendarEvent("Зходження.", "", "Денне відкриття.",
                ContextCompat.getColor(this, R.color.grapes), startTime1, endTime1, true);
        eventList.add(event1);
    }
