### ISSUE TITLE
Failed to find style 'stickyListHeadersListViewStyle' in current theme

### ISSUE THREAD

**Issue by chrisngn** [Tibolte/AgendaCalendarView#86]
I get this error when I open view_agenda.xml and view_agendacalendar.xml. Does anyone know how to fix this?

**Comment by khalid-mahmood** [comment]
@chrisngn 

define a empty style in styles.xml
<style name="stickyListHeadersListViewStyle"></style>
Add to your current theme
<item name="stickyListHeadersListViewStyle">@style/stickyListHeadersListViewStyle</item>

Problem Solved :)

**Comment by chrisngn** [comment]
Thx!

**Comment by chrisngn** [comment]
Fixed
